["protostar.config"]
protostar_version = "0.3.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
logic = ["src/StarknetID.cairo"]
proxy = ["src/Proxy.cairo"]

["protostar.shared_command_configs"]
cairo_path = ["./lib/cairo_contracts/src"]
